MODEL:
  META_ARCHITECTURE: "NLOSDetector"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  PIXEL_MEAN: [ 2.8969,  3.9573, 11.9117]
  PIXEL_STD: [0.7269, 1.5346, 5.0199]
DATASETS:
  TRAIN: ("nlos_2020_train",)
  TEST: ("nlos_2020_train",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  NLOS: True
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  ASPECT_RATIO_GROUPING: False