MODEL:
  META_ARCHITECTURE: "NLOSDetector"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    IN_FEATURES: ["p5", "p6", "p7"]
    FPN_STRIDES: [32, 64, 128]
  PIXEL_MEAN: [ 2.8969,  3.9573, 11.9117]
  PIXEL_STD: [0.7269, 1.5346, 5.0199]
DATASETS:
  TRAIN: ("nlos_2020_train",)
  TEST: ("nlos_2020_train",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (20000, 25000)
  MAX_ITER: 30000
INPUT:
  NLOS: True
  MIN_SIZE_TRAIN: (32,)
  HFLIP_TRAIN: False
DATALOADER:
  ASPECT_RATIO_GROUPING: False