_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "output/fcos/R_50_1x"
DATASETS:
  TRAIN: ("nlos_gt_train",)
  TEST: ("nlos_gt_train",)
MODEL:
  FCOS:
    NUM_CLASSES: 1