_BASE_: "Base-WTN_SFT.yaml"
MODEL:
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
  VOVNET:
    OUT_FEATURES: ["stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "META_WTN_SFT"
  WTN_SFT:
    IN_FEATURES: ["p4", "p5", "p6"]
    NUM_CLASSES: 20
    FPN_STRIDES: [16, 64, 128]
    NUM_CLS_CONVS: 3
    NUM_BOX_CONVS: 3
    NUM_SFT_CONVS: 1
INPUT:
  MIN_SIZE_TRAIN: (160,)
OUTPUT_DIR: "output/fcos/R_50_1x"
DATASAMPLER:
  CLASSWISE_SAMPLER:
    N_WAY: 3
    K_SHOT: 5
    Q_QUERY: 3
SOLVER:
  IMS_PER_BATCH: 4
 