_BASE_: "Base-WTN_SFT.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
#  BACKBONE:
#    NAME: "build_fcos_vovnet_fpn_backbone"
#  VOVNET:
#    OUT_FEATURES: ["stage4", "stage5"]
#  FPN:
#    IN_FEATURES: ["stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "META_WTN_SFT"
  WTN_SFT:
    NUM_CLASSES: 20
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
    NUM_SFT_CONVS: 0
    #FPN_STRIDES: [8, 16, 32, 64, 128]
    #SIZES_OF_INTEREST:  [45, 90, 180, 360]
    #IN_FEATURES: ['p3', 'p4', 'p5', 'p6', 'p7']
INPUT:
  MIN_SIZE_TRAIN: (320,)
OUTPUT_DIR: "output/fcos/R_50_1x"
DATASAMPLER:
  CLASSWISE_SAMPLER:
    N_WAY: 3
    K_SHOT: 2
    Q_QUERY: 2
SOLVER:
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("syntheticSKU_train",)
  TEST: ("syntheticSKU_valid",)
 