_BASE_: "Base-WTN_SFT.yaml"
MODEL:
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage3","stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3","stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "META_WTN_SFT"
  WTN_SFT:
    NUM_CLASSES: 20
    NUM_CLS_CONVS: 3
    NUM_BOX_CONVS: 3
    NUM_SFT_CONVS: 1
OUTPUT_DIR: "output/fcos/R_50_1x"
DATASAMPLER:
  CLASSWISE_SAMPLER:
    N_WAY: 3
    K_SHOT: 2
    Q_QUERY: 5
SOLVER:
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (320,)
DATALOADER:
  NUM_WORKERS: 24
