_BASE_: "Base-ADCR.yaml"
MODEL:
  WEIGHTS: "output/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ADCR:
    TSS: "DATSS"
    CENTER_SAMPLE: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/adcr/R_50_1x"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
