_BASE_: "Base-ADCR.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ADCR:
    TSS: "DATSS"
    CENTER_SAMPLE: False
    FOCAL_EMB: False
    EMB_DIM: 1
    POS_SAMPLE_RATE: -0.5
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/adcr/R_50_1x"
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)
